// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJpYdoQvd3oy4Olj3-G3eW8s-C2PvUjnY',
    appId: '1:511595511713:web:e88467c95ba58640e955e0',
    messagingSenderId: '511595511713',
    projectId: 'carvo-defc5',
    authDomain: 'carvo-defc5.firebaseapp.com',
    storageBucket: 'carvo-defc5.firebasestorage.app',
    measurementId: 'G-K56Y8EJZMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiZaeg_JDxX9BLdmPXpbzUEZkKtAYIgfE',
    appId: '1:511595511713:android:0aca8e1af21c293ce955e0',
    messagingSenderId: '511595511713',
    projectId: 'carvo-defc5',
    storageBucket: 'carvo-defc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQOQBn4D3zsjgAn6RK4aZptxUSEbANiLg',
    appId: '1:511595511713:ios:fd5a046681d1ef0ce955e0',
    messagingSenderId: '511595511713',
    projectId: 'carvo-defc5',
    storageBucket: 'carvo-defc5.firebasestorage.app',
    iosBundleId: 'com.example.carvo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQOQBn4D3zsjgAn6RK4aZptxUSEbANiLg',
    appId: '1:511595511713:ios:fd5a046681d1ef0ce955e0',
    messagingSenderId: '511595511713',
    projectId: 'carvo-defc5',
    storageBucket: 'carvo-defc5.firebasestorage.app',
    iosBundleId: 'com.example.carvo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJpYdoQvd3oy4Olj3-G3eW8s-C2PvUjnY',
    appId: '1:511595511713:web:658f81093b7c8830e955e0',
    messagingSenderId: '511595511713',
    projectId: 'carvo-defc5',
    authDomain: 'carvo-defc5.firebaseapp.com',
    storageBucket: 'carvo-defc5.firebasestorage.app',
    measurementId: 'G-NJN6SZ644X',
  );
}
